@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmMzVjNTJiZC0xZWE5LTQzZjEtYmJlNy0zZTUxNThkOTkyMGEiLCJlbWFpbCI6Im1hcmlhLmdhYnJpZWxhQHRlc3RlLmNvbSIsImlhdCI6MTc3NTkxMjUyNiwiZXhwIjoxNzc1OTk4OTI2fQ.jpQThJ7f4UMY2ZxVQGdkDN2V6vAolWs7Bw4RjpE2x3k

#Ver lista de arquivos do usuário
GET http://localhost:3000/files
Authorization: Bearer {{token}}

### Excluir
DELETE http://localhost:3000/files/2eafc1b0-5843-4b62-8c4d-90a889f8321b
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

### Upload de Arquivo
POST http://localhost:3000/files/upload
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="foto-de-perfil.jpg"
Content-Type: image/jpeg

< c:\Users\José Vine\Pictures\foto-de-perfil.jpg
--boundary--

GET http://localhost:3000/users/b3e873ef-8004-4b74-a72f-67c81c47e91f
Authorization: Bearer {{token}}
Content-Type: application/json

### Criar um usuário

POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "maria.gabriela@teste.com",
  "name": "Maria Gabriela",
  "password": "senha123"
}

### Autenticar um usuário
POST http://localhost:3000/auth
Content-Type: application/json

{
  "email": "maria.gabriela@teste.com",
  "password": "senha123"
}

### Atualizar informações do usuário
PATCH http://localhost:3000/users/19de2c53-d0ab-41ac-9a7e-a3fa7d5f9f46
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "email": "maria.gabriela@teste.com",
  "password": "senha1234",
  "name": "Maria Gabriela"
}

### Excluir um usuário
DELETE http://localhost:3000/users/19de2c53-d0ab-41ac-9a7e-a3fa7d5f9f46
Authorization: Bearer {{token}}
Content-Type: application/json


### Criar um Arquivo (Apenas a referência no banco por enquanto)
POST http://localhost:3000/files
Content-Type: application/json

{
  "name": "foto_perfil.png",
  "url": "/uploads/foto_perfil.png",
  "userId": 1
}